name: Code Checker
on:

  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2


      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Runs a set of commands using the runners shell
      - name: Test compile
        run: cd ./src; javac ./cozycode/capstone/Main.java
